"""time table

Revision ID: 3532a7ae0a4c
Revises: ec86d3bc2145
Create Date: 2021-05-20 00:50:17.783477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3532a7ae0a4c'
down_revision = 'ec86d3bc2145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partOfDay', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partOfDay')
    )
    op.drop_table('time_of_training')
    op.add_column('accounting', sa.Column('time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounting', 'time', ['time_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounting', type_='foreignkey')
    op.drop_column('accounting', 'time_id')
    op.create_table('time_of_training',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('partOfDay', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partOfDay')
    )
    op.drop_table('time')
    # ### end Alembic commands ###
