"""table subs

Revision ID: 3ae0d98f2ad3
Revises: 57d0d97a5950
Create Date: 2021-05-21 22:49:14.736965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae0d98f2ad3'
down_revision = '57d0d97a5950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('pool', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_name'), 'sub', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_name'), table_name='sub')
    op.drop_table('sub')
    # ### end Alembic commands ###
