"""time table

Revision ID: ec86d3bc2145
Revises: 5d8625a44d05
Create Date: 2021-05-20 00:44:20.494391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec86d3bc2145'
down_revision = '5d8625a44d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_of_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partOfDay', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partOfDay')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_of_training')
    # ### end Alembic commands ###
